#!/usr/bin/env python3
"""
Template Lineage Tracker - Trace Template Origins for Generated Files

Answers the question: "What template created this file?"
Enables reverse-lookup of template origins for any generated file,
supporting template upgrade planning, impact analysis, and code family identification.

Usage:
    python3 tools/template_lineage.py <file_path>
    python3 tools/template_lineage.py --files file1.py file2.py file3.py
    python3 tools/template_lineage.py <file_path> --format=json
    python3 tools/template_lineage.py --batch-dir src/
    python3 tools/template_lineage.py --help

Exit Codes:
    0 - Lineage found for all queried files
    1 - Lineage not found for one or more files
    2 - Error (invalid arguments, missing files)

Referenced in:
    - PLANNING/TEMPLATE_VERSIONING_AND_DEPRECATION_POLICY.md:429, 1677, 1680

Author: System
Created: 2025-12-23
"""

import argparse
import sys
import os
import re
import json
from pathlib import Path

# Optional YAML support
try:
    import yaml
    HAS_YAML = True
except ImportError:
    HAS_YAML = False
    yaml = None
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field, asdict
from datetime import datetime

@dataclass
class TemplateLineage:
    """Template lineage information for a file"""
    file_path: str
    has_lineage: bool = False
    template_name: Optional[str] = None
    template_version: Optional[str] = None
    template_full: Optional[str] = None  # e.g., "api-crud@2.3.0"
    code_family: Optional[str] = None
    task_id: Optional[str] = None
    generation_timestamp: Optional[str] = None
    generation_method: Optional[str] = None  # "template", "manual", "unknown"
    sources_checked: List[str] = field(default_factory=list)
    detection_method: Optional[str] = None  # How lineage was determined
    confidence: str = "unknown"  # "high", "medium", "low", "none"

    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)

@dataclass
class BatchResult:
    """Result of batch lineage analysis"""
    files_analyzed: int = 0
    files_with_lineage: int = 0
    files_without_lineage: int = 0
    files_with_errors: int = 0
    code_families: Dict[str, List[str]] = field(default_factory=dict)
    templates_used: Dict[str, List[str]] = field(default_factory=dict)
    results: List[TemplateLineage] = field(default_factory=list)

    def to_dict(self) -> Dict[str, Any]:
        d = asdict(self)
        d['results'] = [r.to_dict() for r in self.results]
        return d

class TemplateLineageTracker:
    """Traces template origins for generated files"""

    # Common template marker patterns in file headers
    TEMPLATE_MARKERS = [
        # System-style markers
        r'Generated from template:\s*([^\n]+)',
        r'Template:\s*([a-zA-Z0-9_-]+)@([0-9.]+)',
        r'@template\s+([a-zA-Z0-9_-]+)(?:@([0-9.]+))?',
        r'Template ID:\s*([a-zA-Z0-9_-]+)',
        # Code family markers
        r'Code Family:\s*([a-zA-Z0-9_-]+)',
        r'@family\s+([a-zA-Z0-9_-]+)',
        # Task markers
        r'Task ID:\s*([0-9.]+)',
        r'Generated by task:\s*([0-9.]+)',
        r'@task\s+([0-9.]+)',
        # Timestamp markers
        r'Generated:\s*(\d{4}-\d{2}-\d{2}(?:[T ]\d{2}:\d{2}:\d{2})?)',
        r'@generated\s+(\d{4}-\d{2}-\d{2})',
    ]

    # File extensions that commonly have template markers
    TEMPLATE_EXTENSIONS = {
        '.py', '.js', '.ts', '.tsx', '.jsx', '.java', '.go', '.rs',
        '.yaml', '.yml', '.json', '.md', '.sh', '.bash', '.zsh'
    }

    def __init__(self, repo_root: Optional[Path] = None, verbose: bool = False):
        self.repo_root = repo_root or Path.cwd()
        self.verbose = verbose

        # Key directories
        self.logbook_tasks = self.repo_root / 'LogBook' / 'progress' / 'tasks'
        self.templates_dir = self.repo_root / 'templates'
        self.archives_golden = self.repo_root / 'archives' / 'templates' / 'golden'

    def log(self, message: str):
        """Log message if verbose"""
        if self.verbose:
            print(f"  [DEBUG] {message}", file=sys.stderr)

    def find_task_manifest(self, file_path: Path) -> Optional[Path]:
        """Find .task/manifest.yaml for a file"""
        # Walk up directories looking for .task/manifest.yaml
        current = file_path.parent
        while current != current.parent:
            manifest = current / '.task' / 'manifest.yaml'
            if manifest.exists():
                return manifest
            current = current.parent
        return None

    def parse_file_header(self, file_path: Path) -> Dict[str, Any]:
        """Parse file header for template markers"""
        result = {
            'template_name': None,
            'template_version': None,
            'code_family': None,
            'task_id': None,
            'generation_timestamp': None,
            'found_markers': []
        }

        try:
            # Read first 50 lines (header area)
            with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
                header_lines = []
                for i, line in enumerate(f):
                    if i >= 50:
                        break
                    header_lines.append(line)
                header = '\n'.join(header_lines)

            # Check for template name@version pattern
            match = re.search(r'Template:\s*([a-zA-Z0-9_-]+)@([0-9.]+)', header)
            if match:
                result['template_name'] = match.group(1)
                result['template_version'] = match.group(2)
                result['found_markers'].append('Template:name@version')

            # Check for standalone template name
            if not result['template_name']:
                match = re.search(r'@template\s+([a-zA-Z0-9_-]+)', header)
                if match:
                    result['template_name'] = match.group(1)
                    result['found_markers'].append('@template')

            # Check for Generated from template:
            if not result['template_name']:
                match = re.search(r'Generated from template:\s*([^\n]+)', header)
                if match:
                    template_spec = match.group(1).strip()
                    if '@' in template_spec:
                        parts = template_spec.split('@')
                        result['template_name'] = parts[0]
                        result['template_version'] = parts[1] if len(parts) > 1 else None
                    else:
                        result['template_name'] = template_spec
                    result['found_markers'].append('Generated from template:')

            # Check for code family
            match = re.search(r'(?:Code Family|@family)[\s:]+([a-zA-Z0-9_-]+)', header)
            if match:
                result['code_family'] = match.group(1)
                result['found_markers'].append('code_family')

            # Check for task ID
            match = re.search(r'(?:Task ID|@task|Generated by task)[\s:]+([0-9.]+)', header)
            if match:
                result['task_id'] = match.group(1)
                result['found_markers'].append('task_id')

            # Check for generation timestamp
            match = re.search(r'(?:Generated|@generated)[\s:]+(\d{4}-\d{2}-\d{2}(?:[T ]\d{2}:\d{2}:\d{2})?)', header)
            if match:
                result['generation_timestamp'] = match.group(1)
                result['found_markers'].append('timestamp')

        except Exception as e:
            self.log(f"Error parsing file header: {e}")

        return result

    def parse_task_manifest(self, manifest_path: Path, file_path: Path) -> Dict[str, Any]:
        """Parse .task/manifest.yaml for template associations"""
        result = {
            'template_name': None,
            'template_version': None,
            'code_family': None,
            'task_id': None
        }

        if not HAS_YAML:
            self.log("YAML parser not available, skipping manifest parsing")
            return result

        try:
            with open(manifest_path, 'r') as f:
                manifest = yaml.safe_load(f)

            if not manifest:
                return result

            # Check for task_id
            result['task_id'] = manifest.get('task_id') or manifest.get('id')

            # Check for template info
            template_info = manifest.get('template') or manifest.get('source_template')
            if template_info:
                if isinstance(template_info, dict):
                    result['template_name'] = template_info.get('name')
                    result['template_version'] = template_info.get('version')
                    result['code_family'] = template_info.get('family') or template_info.get('code_family')
                elif isinstance(template_info, str):
                    if '@' in template_info:
                        parts = template_info.split('@')
                        result['template_name'] = parts[0]
                        result['template_version'] = parts[1] if len(parts) > 1 else None
                    else:
                        result['template_name'] = template_info

            # Check generated_files list for specific file
            generated_files = manifest.get('generated_files', [])
            rel_path = str(file_path.relative_to(manifest_path.parent.parent))
            for gf in generated_files:
                if isinstance(gf, dict):
                    if gf.get('path') == rel_path or gf.get('file') == rel_path:
                        if gf.get('template'):
                            if '@' in gf['template']:
                                parts = gf['template'].split('@')
                                result['template_name'] = parts[0]
                                result['template_version'] = parts[1] if len(parts) > 1 else None
                            else:
                                result['template_name'] = gf['template']

        except Exception as e:
            self.log(f"Error parsing manifest: {e}")

        return result

    def search_logbook_tasks(self, file_path: Path) -> Dict[str, Any]:
        """Search LogBook/progress/tasks/ for task metadata matching file"""
        result = {
            'template_name': None,
            'template_version': None,
            'code_family': None,
            'task_id': None
        }

        if not self.logbook_tasks.exists():
            return result

        if not HAS_YAML:
            self.log("YAML parser not available, skipping LogBook search")
            return result

        try:
            # Get relative path from repo root
            try:
                rel_path = str(file_path.relative_to(self.repo_root))
            except ValueError:
                rel_path = str(file_path)

            # Search task directories
            for task_dir in self.logbook_tasks.iterdir():
                if not task_dir.is_dir():
                    continue

                # Check task.yaml
                for spec_name in ['task.yaml', 'task.yml']:
                    spec_path = task_dir / spec_name
                    if spec_path.exists():
                        try:
                            with open(spec_path, 'r') as f:
                                spec = yaml.safe_load(f)

                            if not spec:
                                continue

                            # Check if this task generated the file
                            outputs = spec.get('outputs', []) or spec.get('generated_files', [])
                            for output in outputs:
                                if isinstance(output, str) and output == rel_path:
                                    result['task_id'] = task_dir.name
                                    result['template_name'] = spec.get('template') or spec.get('source_template')
                                    result['code_family'] = spec.get('code_family') or spec.get('family')
                                    return result
                                elif isinstance(output, dict) and output.get('path') == rel_path:
                                    result['task_id'] = task_dir.name
                                    result['template_name'] = output.get('template') or spec.get('template')
                                    result['code_family'] = spec.get('code_family') or spec.get('family')
                                    return result

                        except Exception as e:
                            self.log(f"Error reading task spec {spec_path}: {e}")

        except Exception as e:
            self.log(f"Error searching LogBook tasks: {e}")

        return result

    def infer_code_family(self, file_path: Path, template_name: Optional[str]) -> Optional[str]:
        """Infer code family from file path or template name"""
        # Try template name patterns
        if template_name:
            family_patterns = {
                'api': ['api', 'endpoint', 'route', 'handler'],
                'auth': ['auth', 'login', 'session', 'token'],
                'crud': ['crud', 'repository', 'dao'],
                'model': ['model', 'entity', 'schema'],
                'service': ['service', 'usecase', 'interactor'],
                'test': ['test', 'spec'],
                'config': ['config', 'settings', 'env'],
                'cli': ['cli', 'command', 'cmd'],
                'hook': ['hook', 'hooks', 'middleware'],
            }

            template_lower = template_name.lower()
            for family, patterns in family_patterns.items():
                if any(p in template_lower for p in patterns):
                    return family

        # Try file path patterns
        path_str = str(file_path).lower()
        if 'api' in path_str or 'endpoint' in path_str:
            return 'api'
        elif 'auth' in path_str:
            return 'auth'
        elif 'model' in path_str or 'entities' in path_str:
            return 'model'
        elif 'service' in path_str:
            return 'service'
        elif 'test' in path_str:
            return 'test'
        elif 'config' in path_str:
            return 'config'
        elif 'cli' in path_str or 'commands' in path_str:
            return 'cli'
        elif 'hooks' in path_str:
            return 'hook'

        return None

    def trace_lineage(self, file_path: Path) -> TemplateLineage:
        """Trace template lineage for a single file"""
        lineage = TemplateLineage(file_path=str(file_path))

        if not file_path.exists():
            lineage.confidence = "none"
            lineage.generation_method = "unknown"
            return lineage

        # Track sources checked
        sources_checked = []

        # 1. Parse file header for template markers
        self.log(f"Checking file header: {file_path}")
        header_info = self.parse_file_header(file_path)
        sources_checked.append("file_header")

        if header_info['template_name']:
            lineage.template_name = header_info['template_name']
            lineage.template_version = header_info['template_version']
            lineage.code_family = header_info['code_family']
            lineage.task_id = header_info['task_id']
            lineage.generation_timestamp = header_info['generation_timestamp']
            lineage.detection_method = "file_header"
            lineage.confidence = "high"
            lineage.has_lineage = True
            lineage.generation_method = "template"

            # Build full template string
            if lineage.template_version:
                lineage.template_full = f"{lineage.template_name}@{lineage.template_version}"
            else:
                lineage.template_full = lineage.template_name

        # 2. Check .task/manifest.yaml
        if not lineage.has_lineage:
            manifest_path = self.find_task_manifest(file_path)
            if manifest_path:
                self.log(f"Checking manifest: {manifest_path}")
                sources_checked.append("task_manifest")
                manifest_info = self.parse_task_manifest(manifest_path, file_path)

                if manifest_info['template_name']:
                    lineage.template_name = manifest_info['template_name']
                    lineage.template_version = manifest_info['template_version']
                    lineage.code_family = manifest_info['code_family']
                    lineage.task_id = manifest_info['task_id']
                    lineage.detection_method = "task_manifest"
                    lineage.confidence = "high"
                    lineage.has_lineage = True
                    lineage.generation_method = "template"

                    if lineage.template_version:
                        lineage.template_full = f"{lineage.template_name}@{lineage.template_version}"
                    else:
                        lineage.template_full = lineage.template_name

        # 3. Search LogBook/progress/tasks/
        if not lineage.has_lineage:
            self.log(f"Searching LogBook tasks...")
            sources_checked.append("logbook_tasks")
            logbook_info = self.search_logbook_tasks(file_path)

            if logbook_info['task_id']:
                lineage.task_id = logbook_info['task_id']
                lineage.template_name = logbook_info['template_name']
                lineage.code_family = logbook_info['code_family']
                lineage.detection_method = "logbook_tasks"
                lineage.has_lineage = logbook_info['template_name'] is not None
                lineage.confidence = "medium" if lineage.has_lineage else "low"
                lineage.generation_method = "template" if lineage.has_lineage else "unknown"

                if lineage.template_name:
                    lineage.template_full = lineage.template_name

        # 4. Infer code family if not found
        if not lineage.code_family:
            lineage.code_family = self.infer_code_family(file_path, lineage.template_name)

        # 5. If no lineage found, mark as manual/unknown
        if not lineage.has_lineage:
            lineage.generation_method = "manual"
            lineage.confidence = "none"

        lineage.sources_checked = sources_checked
        return lineage

    def trace_batch(self, file_paths: List[Path]) -> BatchResult:
        """Trace lineage for multiple files"""
        result = BatchResult()

        for file_path in file_paths:
            try:
                lineage = self.trace_lineage(file_path)
                result.results.append(lineage)
                result.files_analyzed += 1

                if lineage.has_lineage:
                    result.files_with_lineage += 1

                    # Track code families
                    if lineage.code_family:
                        if lineage.code_family not in result.code_families:
                            result.code_families[lineage.code_family] = []
                        result.code_families[lineage.code_family].append(str(file_path))

                    # Track templates used
                    if lineage.template_full:
                        if lineage.template_full not in result.templates_used:
                            result.templates_used[lineage.template_full] = []
                        result.templates_used[lineage.template_full].append(str(file_path))
                else:
                    result.files_without_lineage += 1

            except Exception as e:
                self.log(f"Error processing {file_path}: {e}")
                result.files_with_errors += 1

        return result

    def scan_directory(self, directory: Path, extensions: Optional[set] = None) -> List[Path]:
        """Scan directory for files to analyze"""
        files = []
        exts = extensions or self.TEMPLATE_EXTENSIONS

        for root, dirs, filenames in os.walk(directory):
            # Skip hidden directories and common excludes
            dirs[:] = [d for d in dirs if not d.startswith('.') and d not in {
                'node_modules', '__pycache__', 'venv', '.git', 'dist', 'build'
            }]

            for filename in filenames:
                file_path = Path(root) / filename
                if file_path.suffix in exts:
                    files.append(file_path)

        return files

def print_lineage(lineage: TemplateLineage, format: str = "text"):
    """Print lineage information"""
    if format == "json":
        print(json.dumps(lineage.to_dict(), indent=2))
        return

    print(f"\nFile: {lineage.file_path}")
    print("-" * 50)

    if lineage.has_lineage:
        print(f"  Template: {lineage.template_full or 'unknown'}")
        if lineage.code_family:
            print(f"  Code Family: {lineage.code_family}")
        if lineage.task_id:
            print(f"  Task ID: {lineage.task_id}")
        if lineage.generation_timestamp:
            print(f"  Generated: {lineage.generation_timestamp}")
        print(f"  Detection: {lineage.detection_method} (confidence: {lineage.confidence})")
    else:
        print("  No template lineage found")
        print(f"  Generation method: {lineage.generation_method}")
        print(f"  Sources checked: {', '.join(lineage.sources_checked)}")

def print_batch_result(result: BatchResult, format: str = "text"):
    """Print batch result summary"""
    if format == "json":
        print(json.dumps(result.to_dict(), indent=2))
        return

    print("\n" + "=" * 60)
    print("TEMPLATE LINEAGE BATCH ANALYSIS")
    print("=" * 60)
    print(f"\nFiles analyzed: {result.files_analyzed}")
    print(f"  With lineage: {result.files_with_lineage}")
    print(f"  Without lineage: {result.files_without_lineage}")
    print(f"  Errors: {result.files_with_errors}")

    if result.code_families:
        print("\nCode Families:")
        for family, files in sorted(result.code_families.items()):
            print(f"  {family}: {len(files)} files")

    if result.templates_used:
        print("\nTemplates Used:")
        for template, files in sorted(result.templates_used.items()):
            print(f"  {template}: {len(files)} files")

    if result.files_without_lineage > 0:
        print("\nFiles without lineage:")
        for r in result.results:
            if not r.has_lineage:
                print(f"  - {r.file_path}")

def main():
    parser = argparse.ArgumentParser(
        description='Trace template origins for generated files',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
    # Trace single file
    %(prog)s src/api/handler.py

    # Trace multiple files
    %(prog)s --files src/api/*.py

    # Scan directory
    %(prog)s --batch-dir src/

    # JSON output
    %(prog)s src/api/handler.py --format=json

Exit Codes:
    0 - Lineage found for all files
    1 - Lineage not found for some files
    2 - Error
        """
    )

    parser.add_argument('file', nargs='?', type=Path,
                        help='File to trace lineage for')
    parser.add_argument('--files', '-f', nargs='+', type=Path,
                        help='Multiple files to trace')
    parser.add_argument('--batch-dir', '-d', type=Path,
                        help='Directory to scan for files')
    parser.add_argument('--format', choices=['text', 'json'], default='text',
                        help='Output format')
    parser.add_argument('--verbose', '-v', action='store_true',
                        help='Verbose output')
    parser.add_argument('--repo-root', type=Path, default=Path.cwd(),
                        help='Repository root directory')

    args = parser.parse_args()

    # Validate arguments
    if not any([args.file, args.files, args.batch_dir]):
        parser.print_help()
        sys.exit(2)

    tracker = TemplateLineageTracker(
        repo_root=args.repo_root,
        verbose=args.verbose
    )

    # Collect files to process
    files = []
    if args.file:
        files.append(args.file)
    if args.files:
        files.extend(args.files)
    if args.batch_dir:
        if not args.batch_dir.is_dir():
            print(f"Error: Directory not found: {args.batch_dir}", file=sys.stderr)
            sys.exit(2)
        files.extend(tracker.scan_directory(args.batch_dir))

    if not files:
        print("No files to process", file=sys.stderr)
        sys.exit(2)

    # Process files
    if len(files) == 1:
        lineage = tracker.trace_lineage(files[0])
        print_lineage(lineage, args.format)
        sys.exit(0 if lineage.has_lineage else 1)
    else:
        result = tracker.trace_batch(files)
        print_batch_result(result, args.format)
        sys.exit(0 if result.files_without_lineage == 0 else 1)

if __name__ == '__main__':
    main()
